### PR TITLE
Upgrade grunt-appcache for large projects using bower

### PR DESCRIPTION
**Pull request by ltrillaud**
- move baseUrl from options to data to have a different behavior between webapp and web component
- generate full or partial appcache for web components
- feed appcache with partial manifest file with includes field
- feed appcache with parsing html files with pageslinks field
- auto inject manifest in html pages with setAttribut field

More information in the Readme.md

### CODE REVIEW

**Comment by ltrillaud** [comment]
Hi Daniele
Happy new year.
Can you review this pull-request ?
Thanks in advance
Laurent

**Comment by jmc-88** [comment]
Hi Laurent, I think I'm going to pull this in for now, and maybe refine it a bit more, add some more thorough unit testing before a future release. This is something lacking from my side, I apologize. :)

As of now I don't really like the fact that there's so many ways to specify what to include in the manifest (patterns, literals, pagesLink, includes), so I'll try to clean the latter two.

**Comment by jmc-88** [comment]
Merged in the [bower](https://github.com/canvace/grunt-appcache/tree/bower) branch.

**Comment by ltrillaud** [comment]
Hi Daniele
Thank you for your help to make this pull request better.
Laurent

**Pull request closed without merging**
